// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQJXfdJ71NzSO43oy3UF1A9VqpcPq7KQ',
    appId: '1:830436207960:web:a6e8211e8e0cf5e1aec92d',
    messagingSenderId: '830436207960',
    projectId: 'trucker-0',
    authDomain: 'trucker-0.firebaseapp.com',
    storageBucket: 'trucker-0.appspot.com',
    measurementId: 'G-DGHYFSYPGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0akx-HVOW6Cc_6WVMmrXjOFoFqMgLRI',
    appId: '1:830436207960:android:2e34e670ca4dfef0aec92d',
    messagingSenderId: '830436207960',
    projectId: 'trucker-0',
    storageBucket: 'trucker-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3v7fYe8KPtnDfVf2ztVLIMonBVdTGco',
    appId: '1:830436207960:ios:7b135059b801ed7baec92d',
    messagingSenderId: '830436207960',
    projectId: 'trucker-0',
    storageBucket: 'trucker-0.appspot.com',
    iosBundleId: 'com.example.trucker',
  );
}
